#+title: Doom Emacs Configuration
#+PROPERTY: header-args :tangle config.el :results none
#+startup: content

* General Configuration
** User Info
#+begin_src elisp
(setq user-full-name "David Rambo"
      user-mail-address "davidrambo@mailfence.com")
#+end_src

** Starting window size
Sets the initial window frame's offset in pixels and its size in characters.
#+begin_src elisp
(setq initial-frame-alist '((top . 60) (left . 1262) (width . 92) (height . 50)))
#+end_src

A function to center the frame, written by user g-gundam on the [[https://emacs.stackexchange.com/a/74260][emacs stackexchange]]:
#+begin_src elisp
(defun frame-center ()
  "Center the current frame."
  (interactive)
  (let* ((dw (display-pixel-width))
         (dh (display-pixel-height))
         (f  (selected-frame))
         (fw (frame-pixel-width f))
         (fh (frame-pixel-height f))
         (x  (- (/ dw 2) (/ fw 2)))
         (y  (- (/ dh 2) (/ fh 2))))
    (message (format "dw %d dh %d fw %d fh %d x %d y %d" dw dh fw fh x y))
    (set-frame-position f x y)))
#+end_src

It retrieves the width and height, in pixels, of both the display and the frame.
It then calculates the horizontal offset ~x~ and vertical offset ~y~ as the difference between half of the corresponding width or height values.

For example, my monitor is 3400 pixels wide, and my frame is set to start with a width of 100 characters, or 1016 pixels.
This can be determined by running:
#+begin_src elisp :tangle no
(frame-pixel-width (selected-frame))
#+end_src
** Disable window decoration
#+begin_src elisp
(cond ((eq system-type 'gnu/linux)
       (add-to-list 'default-frame-alist '(undecorated . t)))
      ((eq system-type 'darwin)
       (add-to-list 'default-frame-alist '(undecorated-round . t))))
#+end_src

** Line Numbers
*** Enable line numbers for programming and text modes.
#+begin_src elisp
(setq display-line-numbers-type 'relative)

(defun dr/display-line-numbers-hook ()
  (display-line-numbers-mode 1)
  )
(add-hook 'prog-mode-hook 'dr/display-line-numbers-hook)
(add-hook 'text-mode-hook 'dr/display-line-numbers-hook)
#+end_src

*** Disable line numbers for some modes
Create a function and a hook to disable line numbers in org mode.
#+begin_src elisp
(defun dr/disable-line-numbers-hook ()
  (display-line-numbers-mode 0)
  )
(add-hook 'org-mode-hook 'dr/disable-line-numbers-hook)
#+end_src
*** Highlight Line
Turn off global line highlight.
#+begin_src elisp
(remove-hook 'doom-first-buffer-hook #'global-hl-line-mode)
#+end_src
** Fonts
Set font face and size depending upon the system: ~gnu/linux~ for Linux, ~darwin~ for MacOS.
Be sure to include the decimal when declaring ~:size~.

I tend to use either "SauceCodePro NF" or "JetBrainsMono Nerd Font"
#+begin_src elisp
(cond ((eq system-type 'gnu/linux)
        ;; (setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 13.0)
        (setq doom-font (font-spec :family "IosevkaTerm Nerd Font" :size 14.0)
            doom-variable-pitch-font (font-spec :family "Iosevka Aile" :size 14.0 :weight 'regular)
            doom-serif-font (font-spec :family "Palatino Linotype" :size 16.0)
            doom-big-font (font-spec :size 28.0))
       )
      ((eq system-type 'darwin)
        (setq doom-font (font-spec :family "Iosevka Nerd Font" :size 14.0 :weight 'regular)
            doom-variable-pitch-font (font-spec :family "Iosevka Aile" :size 16.0 :weight 'regular)
            doom-serif-font (font-spec :family "PT Serif" :size 16.0)
            doom-big-font (font-spec :size 28.0))
       ))

(set-face-attribute 'italic nil
                    :slant 'italic
                    :underline nil)
#+end_src
** Theme
#+begin_src elisp
(setq doom-theme 'catppuccin
      catppuccin-enlarge-headings 'nil)

(cond ((eq system-type 'gnu/linux)
             (setq catppuccin-flavor 'macchiato))
            ((eq system-type 'darwin)
             (setq catppuccin-flavor 'latte)))
#+end_src

** Line spacing
#+begin_src elisp
(setq-default line-spacing 0.1)
#+end_src
** Navigate visual lines
#+begin_src elisp
(define-key evil-normal-state-map (kbd "<remap> <evil-next-line>") 'evil-next-visual-line)
(define-key evil-normal-state-map (kbd "<remap> <evil-previous-line>") 'evil-previous-visual-line)
(define-key evil-motion-state-map (kbd "<remap> <evil-next-line>") 'evil-next-visual-line)
(define-key evil-motion-state-map (kbd "<remap> <evil-previous-line>") 'evil-previous-visual-line)
#+end_src
** Zen mode
#+begin_src elisp
(setq +zen-text-scale 0.7)
#+end_src

** Esc always quits
In some prompts and in key sequences, ESC is registered as a potential entry.
This effectively renders it equivalent to C-g.
#+begin_src elisp
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src
** Evil Undo
#+begin_src elisp
(setq  evil-want-fine-undo t
       undo-limit 80000000)
#+end_src

** Window Splitting
From https://github.com/sunnyhasija/Academic-Doom-Emacs-Config
"The following code allows me to choose which buffer I want to see when I split a window. It first does a split to the right, and then opens Ivy and and shows me a preview."
#+begin_src elisp
(setq evil-vsplit-window-right t
      evil-split-window-below t)
(defadvice! prompt-for-buffer (&rest _)
  :after '(evil-window-split evil-window-vsplit evil-window-new)
  (persp-switch-to-buffer))
#+end_src

Split horizontally by default.
#+begin_src elisp
(setq split-height-threshold nil)
(setq split-width-threshold 0)
#+end_src
** Doom modeline
- Set the color of the filename when modified to catppuccin macchiato's "peach."
- Change the height of doom's modeline.
#+begin_src elisp
(custom-set-faces!
  '(doom-modeline-buffer-modified :foreground "#f5a97f"))
(setq doom-modeline-height 28)
#+end_src

* Navigation
** Evil search in folds
https://github.com/doomemacs/doomemacs/issues/6478#issuecomment-1219582005
#+begin_src elisp
(after! evil
  (evil-select-search-module 'evil-search-module 'isearch))
#+end_src

** Counsel Outline
#+begin_src elisp
(define-key evil-normal-state-map (kbd "go") 'counsel-outline)
#+end_src

** Avy
Per tecosaur's configuration, this sets Avy's character prompts to letters in Colemak's homerow:
#+begin_src elisp
(after! avy
  ;; home row priorities: 8 6 4 5 - - 1 2 3 7
  (setq avy-keys '(?t ?e ?i ?s ?r ?o ?a ?n)))
#+end_src
The below keymaps approximate leap.nvim's behavior.
Leap combines evil-snipe's immediate jump with avy's shortcut prompts.
For now I am using doom's builtin approach: snipe to the first character and then use either ~;~ and ~,~ (to traverse matches) or ~C-;~ (to show avy's prompts).
#+begin_src elisp :tangle no
(define-key evil-normal-state-map (kbd "s") 'avy-goto-char-2-below)
(define-key evil-normal-state-map (kbd "S") 'avy-goto-char-2-above)
#+end_src
** Ultra Scroll
#+begin_src emacs-lisp
(ultra-scroll-mode t)
#+end_src
* Org Mode
** Default org file directory
#+begin_src elisp
(setq org-directory "~/notes/")
#+end_src

** Org Modern
This block adds org-mode hooks to enable org-modern.
It also implements some apprearance effects as suggested by minad/org-mode.
#+begin_src elisp
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (setq org-modern-star '("◉" "●" "○" "⁖" "◿" "◌"))
  )
;; (add-hook! org-mode
;;            #'org-modern-mode)
;; (add-hook! 'org-agenda-finalize-hook #'org-modern-agenda)

;; (defcustom org-modern-star '("◉" "○" "◌" "⁖" "◿")
;;         "Overwrite org-modern's provided heading stars."
;;         :type '(repeat string))

;; Add frame borders and window dividers
;; (after! org
;;     (modify-all-frames-parameters
;;     '((right-divider-width . 10)
;;     (internal-border-width . 10)))
;;     (dolist (face '(window-divider
;;                     window-divider-first-pixel
;;                     window-divider-last-pixel))
;;     (face-spec-reset-face face)
;;     (set-face-foreground face (face-attribute 'default :background)))
;;     (set-face-background 'fringe (face-attribute 'default :background))
;; )
#+end_src

** Mixed Pitch
Getting variable fonts to load in org-mode with doom has always been a challenge.
I have never been able to reliably access doom's own variable-pitch font within mixed-pitch-mode settings.
Part of the problem is that mixed-pitch-mode loads before dom's UI module loads.
I use tecosaur's configuration.
*** tecosaur's mixed-pitch-modes
tecosaur's doom emacs literatte configuration is fantastic.
[[https://tecosaur.github.io/emacs-config/config.html#font-face][Its handling of font faces]] and mixed pitch actually works!
#+begin_src elisp
(defvar mixed-pitch-modes '(org-mode LaTeX-mode markdown-mode)
  "Modes that `mixed-pitch-mode' should be enabled in, but only after UI initialisation.")
(defun init-mixed-pitch-h ()
  "Hook `mixed-pitch-mode' into each mode in `mixed-pitch-modes'.
Also immediately enables `mixed-pitch-modes' if currently in one of the modes."
  (when (memq major-mode mixed-pitch-modes)
    (mixed-pitch-mode 1))
  (dolist (hook mixed-pitch-modes)
    (add-hook (intern (concat (symbol-name hook) "-hook")) #'mixed-pitch-mode)))
(add-hook 'doom-init-ui-hook #'init-mixed-pitch-h)

(autoload #'mixed-pitch-serif-mode "mixed-pitch"
  "Change the default face of the current buffer to a serifed variable pitch, while keeping some faces fixed pitch." t)

(after! mixed-pitch

      (setq mixed-pitch-set-height t)
      (setq variable-pitch (font-spec :family "Iosevka Aile"))
      (cond ((eq system-type 'gnu/linux)
            (set-face-attribute 'variable-pitch nil :height 140)
             )
            ((eq system-type 'darwin)
            (set-face-attribute 'variable-pitch nil :height 160)
             )
        )

  (defun mixed-pitch-sans-mode (&optional arg)
    "Change the default face of the current buffer to a sans-serif variable pitch."
    (interactive)
    (let ((mixed-pitch-face 'variable-pitch))
      (mixed-pitch-mode (or arg 'toggle))))

  (defface variable-pitch-serif
    '((t (:family "serif")))
    "A variable-pitch face with serifs."
    :group 'basic-faces)

  (setq mixed-pitch-set-height t)
  (cond ((eq system-type 'gnu/linux)
        (setq variable-pitch-serif-font (font-spec :family "Palatino Linotype" :size 16.0))
       )
      ((eq system-type 'darwin)
        (setq variable-pitch-serif-font (font-spec :family "Palatino" :size 16.0)))
  )
  (set-face-attribute 'variable-pitch-serif nil :font variable-pitch-serif-font)

  (defun mixed-pitch-serif-mode (&optional arg)
    "Change the default face of the current buffer to a serifed variable pitch, while keeping some faces fixed pitch."
    (interactive)
    (let ((mixed-pitch-face 'variable-pitch-serif))
      (mixed-pitch-mode (or arg 'toggle))))

(defadvice! +org-indent--reduced-text-prefixes ()
  :after #'org-indent--compute-prefixes
  (setq org-indent--text-line-prefixes
        (make-vector org-indent--deepest-level nil))
  (when (> org-indent-indentation-per-level 0)
    (dotimes (n org-indent--deepest-level)
      (aset org-indent--text-line-prefixes
            n
            (org-add-props
                (concat (make-string (* n (1- org-indent-indentation-per-level))
                                     ?\s)
                        (if (> n 0)
                             (char-to-string org-indent-boundary-char)
                          "\u200b"))
                nil 'face 'org-indent)))))
)
#+end_src

*** simple mixed-pitch (not in use)
#+begin_src elisp :tangle no
(use-package! mixed-pitch
  :hook
  (org-mode . mixed-pitch-mode))

;; (custom-set-faces! '(variable-pitch :height 160))
#+end_src

Unnecessary alternative approach:
#+begin_src elisp :tangle no
(add-hook! 'org-mode-hook #'mixed-pitch-mode)

(defun dr/org-mode-setup ()
  (variable-pitch-mode 1)
  (set-face-attribute 'variable-pitch nil :height 150)
  (hl-line-mode nil)
  )
(add-hook 'org-mode-hook 'dr/org-mode-setup)
#+end_src

*** custom-theme-set-faces (not in use)
#+begin_src elisp :tangle no
(custom-theme-set-faces
        'user
            '(variable-pitch ((t (:family "Source Sans Pro" :height 140 :weight regular))))
            '(fixed-pitch ((t ( :family "MesloLGSDZ Nerd Font" :height 140)))))
#+end_src

#+begin_src elisp :tangle no
(custom-set-faces!
  '(variable-pitch :family "Source Sans Pro" :height 140 :weight regular))
#+end_src

** Org Appearance
#+begin_src elisp
(after! org
  (setq
   org-hide-emphasis-markers t
   org-pretty-entities t
   org-ellipsis " ▾ "
   ;; From minad/org-modern: Edit settings
   org-auto-align-tags nil
   org-tags-column 0
   org-fold-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t
   org-indent-indentation-per-level 2
   org-startup-folded 'content
   )

   ;; Heading Styles
   (dolist (face
            '((org-level-1 . 1.2)
              (org-level-2 . 1.1)
              (org-level-3 . 1.0)
              (org-level-4 . 1.0)
              (org-level-5 . 1.0)
              (org-level-6 . 1.0)
              (org-level-7 . 1.0)
              (org-level-8 . 1.0)))
   ;; (set-face-attribute (car face) nil :weight 'regular :height (cdr face))
   )
)
#+end_src
*** remove italics in quote and verse blocks
Since ~org-fontify-quote-and-verse-blocks~ obscures markup by making everything italic, I want either:
a. to remove that effect or
b. to set fontify to nil and add a background.
The first should be the most strightforward, as it simply requires setting ~org-quote~'s ~slant~ property to ~regular~.
#+begin_src elisp
(custom-set-faces!
  '(org-quote :inherit doom-variable-pitch-font :slant normal))
(setq org-fontify-whole-block-delimiter-line nil)
#+end_src
Doom emacs's ~custom-set-faces!~ macro makes this trivial.

#+begin_src elisp :tangle no
(custom-set-faces!
  '(fixed-pitch :inherit doom-font :size 15))
#+end_src

*** Adjust block background
It can be difficult to see source code blocks in dark themes, especially in catppuccin.
So I adjust the background manually.

#+begin_src elisp :tangle no
(cond ((eq system-type 'gnu/linux)
       (custom-set-faces! '(org-block :background "#1e2030")))
      ((eq system-type 'darwin)
       (custom-set-faces! '(org-block :background "#dce0e8"))))
#+end_src
*** reveal emphasis markers when editing
#+begin_src elisp
(add-hook! 'org-mode #'org-appear-mode)
#+end_src
** Exporting org files
*** ascii bullets for headings
~org-ascii-bullets~ determines the characters for headlines converted to lists in ASCII export.
#+begin_src elisp
(setq org-ascii-bullets '((ascii ?* ?+ ?-) (latin1 ?* ?+ ?-) (utf-8 ?* ?+ ?-)))
#+end_src
*** org-cv
#+begin_src elisp
(use-package! ox-moderncv
    :init
    (require 'ox-moderncv))
#+end_src
*** latex
Source: https://www.aidanscannell.com/post/org-mode-resume/
#+begin_src elisp
(after! org
  (use-package! ox-latex
    :init
    ;; this code runs immediately
    :config
    ;; this code runs after the package loads
    (setq org-latex-pdf-process
          '("pdflatex -interaction nonstopmode -output-directory %o %f"
            "bibtex %b"
            "pdflatex -interaction nonstopmode -output-directory %o %f"
            "pdflatex -interaction nonstopmode -output-directory %o %f"))
    (setq org-latex-with-hyperref nil) ;; stops org from adding hypersetup{}

    ;; delete unwanted files
    (setq org-latex-logfiles-extensions
          (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf" "acn" "acr" "alg" "glg" "gls" "ist")))
    (unless (boundp 'org-latex-classes)
        (setq org-latex-classes nil)))
  (use-package! ox-extra
    :config
    (ox-extras-activate '(latex-header-blocks ignore-headlines))))
#+end_src
** Superstar (not in use)
Org-modern replaces org-superstar for me.
#+begin_src elisp :tangle no
(use-package! org-superstar-mode
  :custom
    org-superstar-headline-bullets-list '("◉" "○" "◌" "⁖" "◿")
    org-superstar-remove-leading-stars
  :hook (org-mode . org-bullets-mode))

(after! org-superstar
  (setq org-superstar-special-todo-items t
        org-superstar-todo-bullet-alist
                '(("TODO" . 9744)
                  ("[ ]" . 9744)
                  ("DONE" . 9745)
                  ("[X]" . 9745)
                  ("NEXT" . 9744)
                  ("ACTIVE" . )))
    )

(use-package! prettify-symbols-mode
  :custom
; ; (push '("[ ]" .  "☐") prettify-symbols-alist)
  prettify-symbols-alist '(("[ ]" . "☐")
                          ("[-]" . "❍")
                          ("[X]" . "☑"))
  :hook (org-mode . prettify-symbols-mode)
)
#+end_src
** Journal
#+begin_src elisp
(use-package! org-journal
  :init
  (setq org-journal-dir "~/journal/"
        org-journal-file-type 'daily
        org-journal-date-prefix "#+TITLE: "
        org-journal-time-prefix "* "
        org-journal-date-format "%B %d, %Y (%A) "
        org-journal-time-format "%I:%M %p\n"
        org-journal-file-format "%Y-%m-%d.org")

  (setq org-journal-enable-agenda-integration nil)
)
#+end_src

** Agenda
*** Set agenda files
#+begin_src elisp
(setq org-agenda-files '("~/notes/tasks.org"))
#+end_src

*** Keywords
#+begin_src elisp
(after! org
  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "ACTIVE(a)" "|" "DONE(d)")
          (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "REVIEW(v)" "WAIT(w@/!)" "|" "COMPLETED(c)" "CANCELLED(k@)")))

   ;; Agenda styling
   (setq
    org-agenda-todo-keyword-format ""
    org-agenda-tags-column 0
    org-agenda-block-separator ?─
    org-agenda-time-grid
    '((daily today require-timed)
      (800 1000 1200 1400 1600 1800 2000)
      " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
    org-agenda-current-time-string
    "⭠ now ─────────────────────────────────────────────────"

    org-modern-todo-faces
    '(("TODO" . (:foreground "#1c1f24" :background "#ee99a0" :weight regular))
      ("NEXT" . (:foreground "#1c1f24" :background "#eed49f" :slant italic))
      ("ACTIVE" . (:foreground "#1c1f24" :background "#a6da95" :slant italic))
      ("DONE" . (:foreground "#1c1f24" :background "#91d7e3" :weight light :strike-through t))
        ("WAIT" . (:foreground "#1c1f24" :background "#b7bdf8" :weight light)))))
 ;;      ("READ" . (:foreground "#b16286" :weight regular))
 ;;      ("READING" . (:foreground "#8f3f71" :weight regular))
 ;;      ("WAITING" . (:foreground "black" :weight light))))
#+end_src

*** org-agenda icons
This used to use ~all-the-icons-~ functions.
#+begin_src elisp :tangle no
(defun fw/agenda-icon-octicon (name)
  "Returns an all-the-icons-octicon icon"
  (list (nerd-icons-octicon name)))

(defun fw/agenda-icon-faicon (name)
  "Returns an all-the-icons-faicon icon"
  (list (nerd-icons-faicon name)))
#+end_src

#+begin_src elisp
(setq org-agenda-category-icon-alist
      `(("Coding" ,(nerd-icons-faicon "nf-fa-code") nil nil :ascent center)
        ("Home" ,(nerd-icons-octicon "nf-oct-home") nil nil :ascent center)))
#+end_src

*** Set custom commands that show up with "SPC o A":
#+begin_src elisp
(setq org-agenda-custom-commands
  '(("n" "Active and Next Tasks"
     (
      (todo "ACTIVE"
            ((org-agenda-overriding-header "\nActive Tasks\n-----------------")
             (org-agenda-prefix-format "   %i %?-2 t%s")
             (org-agenda-remove-tags nil)))
      (todo "NEXT"
            ((org-agenda-overriding-header "\nNext Tasks\n-----------------")
             (org-agenda-prefix-format "   %i %?-2 t%s")
             (org-agenda-remove-tags nil)))
      (agenda ""
            ((org-deadline-warning-days 8)
             (org-agenda-remove-tags t)
             (org-agenda-current-time-string "ᐊ┈┈┈┈┈┈┈ Now")
             (org-agenda-overriding-header "\nSchedule\n-----------------")))))

    ("h" "Home-related tasks"
       (tags-todo "home"
        ((org-agenda-overriding-header "Home Tasks")
        (org-agenda-remove-tags t)
        ))
     )

    ("o" "OSU"
      ((tags-todo "340"
                 ((org-agenda-overriding-header "Introduction to Databases\n-----------------------")
                  (org-agenda-prefix-format "  %i %?-2 t%s")
                  (org-agenda-remove-tags t)))
      (tags-todo "374"
                 ((org-agenda-overriding-header "Operating Systems I\n-----------------------")
                  (org-agenda-prefix-format "  %i %?-2 t%s")
                  (org-agenda-remove-tags t)))
      ))

    ("w" "Work-related tasks"
     (
      (tags-todo "jobs"
        ((org-agenda-overriding-header "\nJob Application Tasks")))
      (tags-todo "+osu"
        ((org-agenda-overriding-header "\nOSU Tasks")))
     ))

    ;; ("r" "Reading Tasks"
    ;;  ((todo "READING"
    ;;     ((org-agenda-overriding-header "\nCurrently Reading")
    ;;     (org-agenda-remove-tags t)
    ;;     ))
    ;;   (todo "READ"
    ;;     ((org-agenda-overriding-header "\nTo Read")
    ;;     (org-agenda-remove-tags t)
    ;;     ))
    ;;   ))
))
#+end_src

Alternative custom agenda views:
(setq org-agenda-custom-commands
      '(("d" "Dashboard"
         ((agenda "" ((org-deadline-warning-days 7)))
          (todo "NEXT"
    	    ((org-agenda-overriding-header "Next Tasks")))
          (todo "ACTIVE"
    	    ((org-agenda-overriding-header "Active Tasks")))))
        ("n" "Next Tasks"
         ((todo "NEXT"
    	    ((org-agenda-overriding-header "Next Tasks")))))
        ("a" "Active Tasks"
         ((todo "ACTIVE"
    	    ((org-agenda-overriding-header "Active Tasks")))))))
** Roam
#+begin_src elisp
(use-package! org-roam
  :after org
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/notes")
  (org-roam-capture-templates
   '(("d" "default" plain
      "#+filetags: "
      :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n\n%?")
      :unnarrowed t)
   ("e" "ephemeral" entry
      "* ${title}\n:PROPERTIES:\n:ID: %(org-id-new)\n:END:\n%?"
      :target (node "Capture")
      :unnarrowed t
      :empty-lines 1)))

  ;; directory is relative to org-roam-directory
  (org-roam-dailies-directory "../journal/")

  (org-roam-dailies-capture-templates
   '(("d" "default" entry "* %<%I:%M %p>\n%?"
     :target (file+head "%<%Y-%m-%d>.org"
                        "#+title: %<%B %d, %Y (%A)>\n")
     :if-new (file+head "%<%Y-%m-%d>.org"
                        "#+title: %<%B %d, %Y (%A)>\n")
     ;; :unnarrowed t
     )
    )
   )

  (org-roam-node-display-template
          (concat "${title:*} "
                  (propertize "${tags:10}" 'face 'org-tag)))
  :config
  (org-roam-setup))
#+end_src

#+begin_src elisp
(map! :leader
      (:prefix-map ("r" . "Org-Roam commands")
       :desc "Toggle org-roam buffer"
       "t" #'org-roam-buffer-toggle

       :desc "Find or Create Node"
       "f" #'org-roam-node-find

       :desc "Insert Node"
       "i" #'org-roam-node-insert

       :desc "Capture to node"
       "c" #'org-roam-capture

       :desc "Create id for heading node"
       "h" #'org-id-get-create

       :desc "Add alias for node"
       "a" #'org-roam-alias-add

       :desc "Extract to new file"
       "e" #'org-roam-extract-subtree

       ;; :desc "Dailies capture map"
       ;; "d" #'org-roam-dailies-map
       ;; :desc "Capture daily journal"
       ;; "j" #'org-roam-dailies-capture-today
       )
      )
#+end_src

If I were to perform the keybind mappings with use-package, I think it would look like:

:bind (:prefix-map ("SPC r" . "Org-Roam ")
                ("t" . org-roam-buffer-toggle)
                etc.)

I don't know how to integrate descriptions in this way.
** Super Agenda
#+begin_src elisp
(use-package! org-super-agenda
  :after org-agenda
  :config
  (setq
        org-log-done nil
        org-agenda-start-day nil
        org-agenda-span 10
        org-agenda-skip-scheduled-if-done t
        org-agenda-skip-deadline-if-done t
        org-agenda-include-deadlines t
        org-agenda-block-separator 9472
        org-agenda-tags-column 60
        org-agenda-compact-blocks nil
        org-agenda-dim-blocked-tasks t
        org-agenda-start-on-weekday nil
        org-super-agenda-groups nil
        )
  (org-super-agenda-mode)
)
#+end_src

#+begin_src emacs-lisp :tangle no
(let ((org-super-agenda-groups
       '((:auto-category t))))
  (org-agenda-list))
#+end_src
** Turn off git-gutter
Git-gutter-mode messes with the visual line traversal, so I turn it off in org-mode.
#+begin_src elisp
(after! git-gutter
  (setq git-gutter:disabled-modes '(org-mode image-mode)))
#+end_src
** Turn off company
Company's autocompletion is very annoying when writing, so I turn it off in org-mode.
#+begin_src elisp
(setq company-global-modes '(not org-mode))
#+end_src

** Visual Column Mode
#+begin_src elisp
(defun center-visual-fill ()
  (setq fill-column 84)
  (setq visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(add-hook 'visual-line-mode-hook #'center-visual-fill)

(map! :leader
      :desc "visual-fill-column-mode"
      "W" #'visual-fill-column-mode)
#+end_src

** Org Mappings
*** Open Task File
Function to open tasks.org plus mapping.
#+begin_src elisp
(defun open-task-file ()
  "Open tasks.org file."
  (interactive)
  (find-file-existing "~/notes/tasks.org"))
(global-set-key (kbd "C-c t") 'open-task-file)
#+end_src

*** Open hours log
Function to open my timedot hours log and turn on org-mode, plus a mapping to call it.
#+begin_src elisp
(defun open-hours-log ()
  "Open hours-log.org file."
  (interactive)
  (find-file-existing "~/notes/time_ledger.timedot")
  (org-mode))
(global-set-key (kbd "C-c h") 'open-hours-log)
 #+end_src
*** Toggle subtree narrow
#+begin_src elisp
(map! :leader
      :desc "Toggle narrow subtree"
      "t n" #'org-toggle-narrow-to-subtree)
#+end_src
*** Fix =z o= to open fold
=z o= stopped working to call ~+org/open-fold~.
One workaround is to override fold-open in org mode ([[https://github.com/doomemacs/doomemacs/issues/6737#issuecomment-1265815504][source]]).
#+begin_src elisp
(map! :after evil-org :map evil-org-mode-map
      :nv "z o" #'evil-open-fold)
#+end_src
** Auto-tangle
#+begin_src elisp
(defun efs/org-babel-tangle-config ()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "~/.config/emacs-from-scratch/config.org"))
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook! org-mode (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))
#+end_src
* Packages
** Geiser
On Fedora, Guile Scheme is installed as ~guile3.0~, so geiser does not find it by default.
#+begin_src elisp
(setq geiser-guile-binary "/usr/bin/guile3.0")
#+end_src
** Thesaurus
#+begin_src elisp
(use-package! powerthesaurus
  :defer t)
#+end_src
